### ISSUE TITLE
Arduino-BASIC serial terminal

### ISSUE THREAD

**Issue by vitasam** [jamesrussell42/BASICcomp#1]
Hi,
it looks like the best way of having serial terminal for intput/output is to use a terminal program that supports VT100 with correct ANSI escape sequences. Not that simple Serial Monitor from IDE.
Some [discussion](https://forum.arduino.cc/index.php?topic=107488.0).

**Comment by vitasam** [comment]
I did a quick test of this [VT100 library](https://github.com/RobTillaart/Arduino/tree/master/libraries/VT100) with following code:

```
#include "VT100.h"

void setup()
{
  Serial.begin(115200);
  Serial.println("VT100 demo sketch");
  delay(1000);
  
  Serial.print(CLS);
  Serial.println("Hello World");
  Serial.print(OFF);
  Serial.println("Goodbye");
  delay(100);
  
  Serial.print(BOLD);
  Serial.println("bold - Hello World");
  Serial.print(OFF);
  Serial.println("Goodbye");
  delay(100);
  
  Serial.print(LOWINTENS);
  Serial.println("lowintense - Hello World");
  Serial.print(OFF);
  Serial.println("Goodbye");
  delay(100);
  
  Serial.print(UNDERLINE);
  Serial.println("underline - Hello World");
  Serial.print(OFF);
  Serial.println("Goodbye");
  delay(100);
  
  Serial.print(BLINK);
  Serial.println("blink - Hello World");
  Serial.print(OFF);
  Serial.println("Goodbye");
  delay(100);
  
  Serial.print(REVERSE);
  Serial.println("reverse - Hello World");
  Serial.print(OFF);
  Serial.println("Goodbye");

  delay(10000);

  Serial.println("Clean screen and set cursor to home");

  delay(10000);  
  Serial.print(CLS);
  Serial.println("One");
  Serial.println("Two");  
  Serial.println("Goodbye");    
  
  // experimental section (does not work yet)
  /*
  Serial.print(CUD(3));
  Serial.println("Cursor Down 3 - Hello World");
  Serial.print(OFF);
  Serial.println("Goodbye");  
  delay(100);
  
  Serial.print(GOTOXY(3,2));
  Serial.println("gotoxy 3,2 - Hello World");
  Serial.print(OFF);
  Serial.println("Goodbye");  

  Serial.print(GOTOXY(3,1));
  Serial.println("gotoxy 3,1 - Hello World");
  Serial.print(OFF);
  Serial.println("Goodbye");  
*/  
  delay(100);  
}

void loop()
{
  delay(100);    
}
// END OF FILE
```

Result from Linux Minicom console terminal program (Minicom was in VT102 mode, apparently **Low Intense** and **Blinking** do not work):
![vt100terminal_arduino](https://user-images.githubusercontent.com/5597505/47848451-010aeb00-ddd7-11e8-8e82-d41d9c6c0b15.png)
![vt100_term_home](https://user-images.githubusercontent.com/5597505/47848460-05370880-ddd7-11e8-8506-6d57e6e799cb.png)

**Comment by jamesrussell42** [comment]
That's a pretty useful library nice find.  I didn't think you were going to start working on this so soon, thanks :)

I had to add the line Serial.print(HOME); after the CLS in set to home section but it worked great using MacTerm.  Blinking also didn't work but that's not the end of the world.

I will have a look at how I can get my serial terminal screen to receive VT100 serial correctly.

**Comment by vitasam** [comment]
No problem :)
Yes, maybe it is safe to add HOME and CLS together, in order to be compatible with most of terminals.

I will slowly continue to play with Arduino-Basic, let's see how it will go. By the way, I have found local copy of my abandoned GIT with stm32 "blue pill" version of Arduino-Basic. I did some refactoring of sources - moved host, HAL, lcd, etc. in to separate files. Also I've added PC version of the host (cross-platform Code BLocks project) - it is easier to develop Basic features on a PC. If you want I can prepare pull request for this GIT repo.

**Comment by jamesrussell42** [comment]
Looks like someone has already made one: https://github.com/TheLancashireman/lcdTerminal

I will flash to my Serial monitor and see if it works.

**Comment by jamesrussell42** [comment]
> No problem :)
> Yes, maybe it is safe to add HOME and CLS together, in order to be compatible with most of terminals.
> 
> I will slowly continue to play with Arduino-Basic, let's see how it will go. By the way, I have found local copy of my abandoned GIT with stm32 "blue pill" version of Arduino-Basic. I did some refactoring of sources - moved host, HAL, lcd, etc. in to separate files. Also I've added PC version of the host (cross-platform Code BLocks project) - it is easier to develop Basic features on a PC. If you want I can prepare pull request for this GIT repo.

Just saw this sorry.  Please do go ahead with the pull, that would be great. Thanks.

**Comment by vitasam** [comment]
LCDterminal looks really great. Maybe I can re-use it in the u6502 project as well.

With stm32basic - yep, I will prepare it

**Comment by jamesrussell42** [comment]
Yeah, just had a little play with it, got two arduinos talking to each other over VT100 serial.  I will need to play with the screen buffer on the display side to handle line breaks if it goes over 20 columns but that should be relatively simple to get working.

Now to try and figure out how to get Arduino Basic sending VT100 :)

**Comment by jamesrussell42** [comment]
Actually looks like I just needed to set it to increment row++if it goes over 20 columns.  Working great.

**Comment by vitasam** [comment]
Just found another library for [ANSI/VT220 terminal control over (typically) a serial connection](https://github.com/nottwo/BasicTerm).

**StatusMonitor** example from the library to Minicom:
![image](https://user-images.githubusercontent.com/5597505/47895528-90fd7300-de71-11e8-8f7d-b28453a2b9ac.png)

It can read keyboard in a main loop:
```
    key = term.get_key();
    switch(key) {
        case ' ':
            /* Spacebar: toggle LED */
            digitalWrite(LED, !digitalRead(LED));
            break;
        case '\f':
            /* Ctrl-L: redraw screen */
            term.cls();
            break;
    }
```

**Comment by jamesrussell42** [comment]
That looks good, i'll have a play around with it.

**Comment by vitasam** [comment]
I created a pull request with BasicTerm for Arduino-Basic:
![image](https://user-images.githubusercontent.com/5597505/47957327-75eb4a00-dfbc-11e8-8599-b266a41e64a1.png)

**Comment by jamesrussell42** [comment]
Sorry for the delay! Work went a bit crazy this week.  I've merged.  I'll have a play later thanks :)

**Comment by vitasam** [comment]
No problem! No need to answer immediately :)

I've found problem with Backspace, seems that the terminal library does not support it yet

**Comment by zrafa** [comment]
> I created a pull request with BasicTerm for Arduino-Basic:
> ![image](https://user-images.githubusercontent.com/5597505/47957327-75eb4a00-dfbc-11e8-8599-b266a41e64a1.png)

Is it possible to use Arduino-Basic with uart and PC? Is it your basicTerm? How do we use that option? (just minicom o screen on PC for input/output and arduino-basic on arduino)

**Comment by vitasam** [comment]
> 
> 
> > I created a pull request with BasicTerm for Arduino-Basic:
> > ![image](https://user-images.githubusercontent.com/5597505/47957327-75eb4a00-dfbc-11e8-8599-b266a41e64a1.png)
> 
> Is it possible to use Arduino-Basic with uart and PC? Is it your basicTerm? How do we use that option? (just minicom o screen on PC for input/output and arduino-basic on arduino)

This screenshot is from Arduino-Basic, running on a PC. It was long time ago, but if I remember correctly, enabling of `ANSI_VT220_TERMINAL_OUTPUT` compilation flag should output BASIC console from Arduino to UART, please take a look [in to the last commit](https://github.com/jamesrussell42/BASICcomp/commit/ac82762d9e416c7f00310a19a12d2aa6003c9bba).
