### ISSUE TITLE
Stm32Basic

### ISSUE THREAD

**Issue by vitasam** [jamesrussell42/BASICcomp#3]
Hi, 
I've created pull request

**Comment by jamesrussell42** [comment]
Great thanks, I have merged and will take a look through.

**Comment by vitasam** [comment]
Hi,
could you update your repo and links, this is an updated repo of stm32basic?
https://github.com/vitasam/stm32basic

**Comment by jamesrussell42** [comment]
Sure thing.  I complely forgot about this project when I was changing jobs.  I'll re-aquaint myself with it tomorrow and update.

**Comment by vitasam** [comment]
Great!
I also decided to get dust off `stm32basic `project. Basically I have simplified it (removed all other targets like PC, terminal IO etc.), and added SD card support for .BAS files.
